apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-bootstrap
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ingress-nginx/
    repoURL: https://github.com/tfinardi/ftd2022-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
