apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/microservices-demo/microservices-demo'
    path: deploy/kubernetes/manifests
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sock-shop
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
